1. PENGGUNAAN NUMPY

In [2]:
import numpy as np

In [3]:
# Buat array
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.shape)
print(arr.dtype)

[1 2 3 4 5]
(5,)
int64


In [4]:
# Operasi matematika — berlaku ke semua elemen sekaligus
print(arr * 2)
print(arr + 10)
print(arr ** 2)

[ 2  4  6  8 10]
[11 12 13 14 15]
[ 1  4  9 16 25]


In [5]:
# Array 2D (matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix.shape)  # (2, 3) → 2 baris, 3 kolom

(2, 3)


In [6]:
# Slicing
print(arr[1:4])       # index 1 sampai 3
print(matrix[0, :])   # baris pertama, semua kolom

[2 3 4]
[1 2 3]


2. PENGGUNAAN PANDAS

In [7]:
import pandas as pd

In [8]:
# Buat DataFrame manual
data = {
    'nama': ['Andi', 'Budi', 'Citra', 'Dian'],
    'usia': [25, 30, 22, 28],
    'gaji': [5000000, 8000000, 4500000, 7000000]
}

In [9]:
df = pd.DataFrame(data)
print(df)
print(df.shape)        # jumlah baris dan kolom
print(df.dtypes)       # tipe data tiap kolom
print(df.describe())   # statistik dasar

    nama  usia     gaji
0   Andi    25  5000000
1   Budi    30  8000000
2  Citra    22  4500000
3   Dian    28  7000000
(4, 3)
nama      str
usia    int64
gaji    int64
dtype: object
        usia          gaji
count   4.00  4.000000e+00
mean   26.25  6.125000e+06
std     3.50  1.652019e+06
min    22.00  4.500000e+06
25%    24.25  4.875000e+06
50%    26.50  6.000000e+06
75%    28.50  7.250000e+06
max    30.00  8.000000e+06


In [10]:
# Filtering
print(df[df['usia'] > 25])           # filter baris
print(df[['nama', 'gaji']])          # pilih kolom tertentu

   nama  usia     gaji
1  Budi    30  8000000
3  Dian    28  7000000
    nama     gaji
0   Andi  5000000
1   Budi  8000000
2  Citra  4500000
3   Dian  7000000


In [11]:
# Tambah kolom baru
df['gaji_juta'] = df['gaji'] / 1_000_000
print(df)

    nama  usia     gaji  gaji_juta
0   Andi    25  5000000        5.0
1   Budi    30  8000000        8.0
2  Citra    22  4500000        4.5
3   Dian    28  7000000        7.0


In [12]:
# Sorting
print(df.sort_values('gaji', ascending=False))

    nama  usia     gaji  gaji_juta
1   Budi    30  8000000        8.0
3   Dian    28  7000000        7.0
0   Andi    25  5000000        5.0
2  Citra    22  4500000        4.5
